-- Full export of 3 unused backup tables before dropping them, taken 2026-08-26T03:11:41.425Z.
-- To restore any of these: run the CREATE TABLE for it first (see below), then these INSERTs.

-- Schema for dbo.device_replacement_backup:
--   replacement_id int NOT NULL
--   employee_id int NOT NULL
--   old_equipment_id int NULL
--   old_warranty_status varchar(30) NULL
--   old_device_status varchar(30) NULL
--   old_device_location varchar(50) NULL
--   old_bag bit NULL
--   old_mouse bit NULL
--   old_keyboard bit NULL
--   new_equipment_id int NOT NULL
--   new_warranty_status varchar(30) NULL
--   new_owner_location varchar(100) NULL
--   new_bag bit NULL
--   new_mouse bit NULL
--   new_keyboard bit NULL
--   replacement_date date NULL

-- dbo.device_replacement_backup: 29 rows
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (4, 74, 384, NULL, 'Working', 'IT Stock', 0, 1, 1, 467, 'Working', NULL, 1, 1, 1, NULL);
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (5, 94, 401, NULL, 'Working', 'IT Stock', 0, 0, 0, 453, 'Working', NULL, 1, 1, 1, '2025-06-19 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (6, 91, 415, NULL, 'Working', 'IT Stock', 0, 0, 0, 450, 'Working', NULL, 1, 1, 1, '2025-06-24 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (7, 95, 426, NULL, 'Working', 'IT Stock', 0, 1, 0, 454, 'Working', NULL, 1, 1, 1, NULL);
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (8, 93, 449, NULL, 'Working', 'IT Stock', 0, 1, 0, 452, 'Working', NULL, 1, 1, 1, '2025-06-19 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (11, 29, 293, NULL, 'Working', 'IT Stock', 0, 0, 0, 62, 'Working', NULL, 1, 1, 1, '2025-06-12 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (14, 111, 299, NULL, 'Working', 'IT Stock', 0, 0, 0, 476, 'Working', NULL, 1, 1, 1, '2025-06-12 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (15, 110, 580, NULL, 'Working', 'IT Stock', 0, 0, 0, 475, 'Working', NULL, 1, 1, 1, '2025-06-19 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (16, 112, 574, NULL, 'Working', 'IT Stock', NULL, NULL, NULL, 477, 'Working', NULL, 1, 1, 1, NULL);
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (17, 73, 579, NULL, 'Working', 'IT Stock', 0, 0, 0, 464, 'Working', NULL, 1, 1, 1, '2025-06-20 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (19, 40, 71, NULL, 'Working', 'IT Stock', 0, 0, 0, 73, 'Working', NULL, 1, 1, 1, NULL);
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (23, 195, 785, NULL, 'Working', 'IT Stock', NULL, NULL, NULL, 451, 'Working', NULL, 1, 1, 1, '2025-06-18 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (24, 71, NULL, NULL, 'Working', 'IT Stock', NULL, NULL, NULL, 463, 'Working', NULL, 1, 1, 1, NULL);
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (25, 25, NULL, NULL, 'Working', 'IT Stock', NULL, NULL, NULL, 471, 'Working', NULL, 1, 1, 1, NULL);
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (29, 22, 520, NULL, 'Working', NULL, 0, 0, 1, 478, NULL, 'IT Stock', 1, 1, 1, '2025-06-12 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (30, 198, 533, NULL, 'Working', NULL, 0, 1, 1, 476, NULL, 'IT Stock', 1, 1, 1, '2025-06-16 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (32, 200, 445, NULL, 'Working', NULL, 0, 0, 0, 461, NULL, 'IT Stock', 1, 1, 1, '2025-06-19 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (33, 208, 444, NULL, 'Working', NULL, 0, 0, 0, 474, NULL, 'IT Stock', 1, 1, 1, '2025-06-18 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (34, 203, 80, NULL, 'Working', NULL, 0, 0, 0, 466, NULL, 'IT Stock', 1, 1, 1, '2025-06-19 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (35, 199, 523, NULL, 'Working', NULL, 0, 1, 0, 458, NULL, 'IT Stock', 1, 1, 1, '2025-06-19 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (36, 202, 432, NULL, 'Working', NULL, 1, 1, 0, 465, NULL, 'IT Stock', 1, 1, 1, '2025-06-19 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (37, 207, 410, NULL, 'Working', NULL, 0, 1, 1, 473, NULL, 'IT Stock', 1, 1, 1, '2025-06-18 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (38, 206, 408, NULL, 'Working', NULL, 0, 1, 1, 472, NULL, 'IT Stock', 1, 1, 1, '2025-06-18 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (44, 28, 535, NULL, 'Working', NULL, 0, 1, 0, 459, NULL, 'IT Stock', 1, 1, 1, '2025-06-19 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (45, 197, 573, NULL, 'Working', NULL, 0, 1, 0, 456, NULL, 'IT Stock', 1, 1, 1, '2025-06-25 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (46, 205, 569, NULL, 'Working', NULL, 0, 0, 0, 469, NULL, 'IT Stock', 1, 1, 1, '2025-06-25 00:00:00');
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (51, 204, 531, NULL, 'Working', NULL, 0, 1, 0, 468, NULL, 'IT Stock', 1, 1, 1, NULL);
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (52, 196, 572, NULL, 'Working', NULL, 0, 0, 0, 455, NULL, 'IT Stock', 1, 1, 1, NULL);
INSERT INTO dbo.device_replacement_backup ([replacement_id], [employee_id], [old_equipment_id], [old_warranty_status], [old_device_status], [old_device_location], [old_bag], [old_mouse], [old_keyboard], [new_equipment_id], [new_warranty_status], [new_owner_location], [new_bag], [new_mouse], [new_keyboard], [replacement_date]) VALUES (57, 201, 482, NULL, 'Working', NULL, 0, 1, 0, 462, NULL, 'IT Stock', 1, 1, 1, NULL);

-- Schema for dbo.custom_field_backup:
--   field_id int NOT NULL
--   category_id int NOT NULL
--   field_key varchar(50) NOT NULL
--   field_label nvarchar(100) NOT NULL
--   field_type varchar(20) NOT NULL
--   is_required bit NOT NULL
--   sort_order int NOT NULL
--   created_at datetime NOT NULL
--   created_by nvarchar(100) NULL

-- dbo.custom_field_backup: 1 rows
INSERT INTO dbo.custom_field_backup ([field_id], [category_id], [field_key], [field_label], [field_type], [is_required], [sort_order], [created_at], [created_by]) VALUES (1, 9, 'rack_position', 'Rack Position', 'text', 0, 99, '2026-08-06 08:29:24', 'Tplus');

-- Schema for dbo.employee_position_backup:
--   employee_id int NOT NULL
--   full_name varchar(150) NOT NULL
--   staff_code varchar(30) NULL
--   phone varchar(30) NULL
--   sex varchar(10) NULL
--   location varchar(50) NULL
--   position nvarchar(255) NULL
--   department_id int NULL
--   is_active bit NOT NULL
--   left_date date NULL

-- dbo.employee_position_backup: 203 rows
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (1, 'Boing / Phengmalai', NULL, NULL, NULL, 'Floor1', NULL, 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (2, 'Maneekone', NULL, NULL, NULL, 'Floor2', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (3, 'Manisone Phoumseanouane', NULL, NULL, NULL, 'Floor1', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (5, 'Phoutthanakone Kindavong', NULL, NULL, NULL, 'Floor3', NULL, 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (6, 'Saysombath Chanthamaly', NULL, NULL, NULL, 'Floor3', 'Cashier', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (7, 'Somphavanh Thoummavong', NULL, NULL, 'Male', 'Floor2', 'Reporting & Enterprise Systems Manager', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (8, 'Sophaphone', NULL, NULL, NULL, 'Floor1', NULL, 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (9, 'Souphany Vanhmany', NULL, NULL, NULL, 'Floor2', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (10, 'Southathip Inthavong', NULL, NULL, NULL, 'VTE', 'Administration Coordinator', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (11, 'Thongkham Cheansou', NULL, NULL, 'Male', 'Floor2', 'Charging and VAS Systems Manager', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (12, 'Tui vilaylack', NULL, NULL, NULL, 'Floor2', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (13, 'Visana Chanthavong', NULL, NULL, NULL, 'Floor1', 'Ccare Team', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (14, 'Vonekham Luangxay', NULL, NULL, NULL, 'VTE', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (15, 'Lodtana Saysomboun', NULL, NULL, NULL, 'Floor2', NULL, 8, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (16, 'Bounthom Keochampa', NULL, NULL, NULL, 'Floor2', 'DMS Coordinator', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (17, 'Kaisone Inthisane', NULL, NULL, NULL, 'PS', NULL, 10, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (18, 'Thiliphone Xaysimthong', NULL, NULL, NULL, 'IT Center', 'Treasury', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (19, 'Poupe Soulivong', NULL, NULL, NULL, 'Floor1', 'Receptionist', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (20, 'Souphaphone Thammavong', NULL, NULL, NULL, 'KHM', 'Customer Care Agent', 2, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (21, 'Chue Yang', NULL, NULL, NULL, 'Floor2', NULL, 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (22, 'Fongmoua', 'VIP18-1030', NULL, 'Male', 'LTC', 'IT Support', 6, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (23, 'Santisouk Phaphongphan', NULL, NULL, 'Male', 'LTC', 'Enterprise System Administrator', 6, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (25, 'Bounta Vongsikeo', NULL, NULL, NULL, 'Floor2', 'Regional Sales Manager North', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (26, 'Kesone Luanglath', NULL, NULL, NULL, 'Floor2', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (27, 'Koxiong Yongthaoxiong', NULL, NULL, NULL, 'Floor2', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (28, 'Lathdavone Sisouvanh', NULL, NULL, NULL, 'Floor2', 'Sale Admin', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (29, 'Mengvang Xaitengvang', NULL, NULL, NULL, 'Floor2', 'FTTH Coordinator', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (30, 'Na Khamsulida', NULL, NULL, NULL, 'VTE', 'Senior Sale Representative', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (31, 'Phet Phimphuangphaeng', NULL, NULL, NULL, 'VTE', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (32, 'Phouthanong Sybounmala', NULL, NULL, NULL, 'Floor2', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (33, 'Saosanga Thammavongsa', NULL, NULL, NULL, 'Floor2', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (34, 'Sengthavy Mahavong', NULL, NULL, NULL, 'Floor2', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (35, 'Somkeo Khantisai', NULL, NULL, NULL, 'VTE', 'Back office Assistant', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (36, 'Songkan', NULL, NULL, NULL, 'Floor2', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (37, 'Thongphala Sisongkham', NULL, NULL, NULL, 'Floor2', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (38, 'Unyu Seanganan', NULL, NULL, NULL, 'VTE', 'DMS Coordinator', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (39, 'Vidasouk Lorphengyong', NULL, NULL, NULL, 'Floor2', 'ISP Coordinator', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (40, 'Vilaiphone Souvannalath', NULL, NULL, NULL, 'Floor2', 'Commission and Reporting Coordinator', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (41, 'Vilaphone Thathilath', NULL, NULL, NULL, 'Floor2', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (42, 'Voneny', NULL, NULL, NULL, 'Floor2', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (44, 'Somchan Boulidam', NULL, NULL, NULL, 'BLK', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (46, 'Saythong Xayyalad', NULL, NULL, NULL, 'XSB', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (47, 'Song Phimmasone', NULL, NULL, NULL, 'XSB', NULL, 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (49, 'Nilane Khamsaveng', NULL, NULL, NULL, 'VTE', 'Credit and Collection Executive', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (50, 'Ketsoulin Sounbundith', NULL, NULL, NULL, 'VTE', 'Stock Management Officer', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (51, 'Dennapha', NULL, NULL, NULL, 'VTE', 'ບໍລິການລູກຄ້າອົງກອນ', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (52, 'Norkham Phachanla', NULL, NULL, NULL, 'LTC', 'Call Center Assistant Manager', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (53, 'Pany Bounliyaphanh', NULL, NULL, NULL, 'LNT', 'C-Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (54, 'Tounta Kongsombath', NULL, NULL, NULL, 'SVK', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (55, 'Phothisa Vongsouvanhkhenkhansay', NULL, NULL, NULL, 'VTE', 'C-care Onsite Support', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (56, 'Yeema Thammavong', NULL, NULL, NULL, 'HOP', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (57, 'Vin Philavong', NULL, NULL, NULL, 'XKH', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (58, 'Vannida Chanthala', NULL, NULL, NULL, 'VTE', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (59, 'Somsanouk Singvongsa', NULL, NULL, NULL, 'ODX', 'Customer Care Agent', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (60, 'somphein Boungium', NULL, NULL, NULL, 'VTE', 'Inventory Supervisor', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (61, 'Siamphone Thammachai', NULL, NULL, NULL, 'PSL', 'C-Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (62, 'Phonevilay Tamanyvong', NULL, NULL, NULL, 'XSB', 'C-Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (63, 'Douangphathay Detthongthip', NULL, NULL, NULL, 'SVK', 'C-Care', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (64, 'Souksavanh Inseeiengmai', NULL, NULL, NULL, 'SVK', 'Admin Savannakhet', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (65, 'Thin Thongsathit', NULL, NULL, NULL, 'CPS', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (67, 'Khannakhone Syvankham', NULL, NULL, NULL, 'CPS', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (68, 'Kenta Xaiyavong', NULL, NULL, NULL, 'KHM', 'Administration Officer', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (69, 'Khomphet Souliyavong', NULL, NULL, NULL, 'CPS', 'Corporate Sales Representative', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (70, 'Phimmasone Bouaphansouk', NULL, NULL, NULL, 'KHM', 'Administration Assistant', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (71, 'Oudavieng Siphaphone', NULL, NULL, NULL, 'LPB', 'Administration Officer', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (72, 'thongphak', NULL, NULL, NULL, 'VTE', 'Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (73, 'Hulza', NULL, NULL, NULL, 'VTE', 'C-Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (74, 'Siard Thammavong', NULL, NULL, NULL, 'VTE', 'Beeline Point Coordinator', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (75, 'Viladeth Dedthongthip', NULL, NULL, NULL, 'CPS', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (76, 'Sakdavone Sonethavong', NULL, NULL, NULL, 'CPS', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (77, 'Soulanna Vannavong', NULL, NULL, NULL, 'CPS', 'C-Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (78, 'Viphada Phanphouthone', NULL, NULL, NULL, 'VTE', 'AR Accountant', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (79, 'Souksamai Khomsan', NULL, NULL, NULL, 'VTE', 'VAS Assistant Officer', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (80, 'Asanai Thanuchuk', NULL, NULL, NULL, 'VTE', 'Inventory Officer', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (81, 'Souchinda Manyvanh', NULL, NULL, NULL, 'VTE', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (82, 'Noud Saiykham', NULL, NULL, NULL, 'VTE', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (83, 'Bounphahaksa Sansouk', NULL, NULL, NULL, 'CPS', 'Administrative & Inventory Officer', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (84, 'Vanxaysomsouk Manhsaengthong', NULL, NULL, NULL, 'VTE', 'Building in Charge', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (85, 'Sengthavy Mavavong', NULL, NULL, NULL, 'VTE', 'Sales Logistic Officer', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (86, 'Bounthavy Sanlaseun', NULL, NULL, NULL, 'VTE', 'IT Support', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (88, 'bounngern Sordaluck', NULL, NULL, NULL, 'VTE', 'Administration Coordinator and ISO Operation Manager', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (89, 'CHANDAY SINGMAVONG', NULL, NULL, NULL, 'VTE', 'ບໍລິການລູກຄ້າ', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (90, 'Khambui Manivanh', NULL, NULL, NULL, 'VTE', 'Senior Regional Sale (KHM)', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (91, 'Vilavanh Vongsay', NULL, NULL, NULL, 'LTC', 'Complaint Management Officer', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (92, 'Phayvanh Chittathamh', NULL, NULL, NULL, 'VTE', 'Head of Administration', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (93, 'Nilamon', NULL, NULL, NULL, 'VTE', 'Acting Inventory Manager', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (94, 'Niphaphone Phonesavanh', NULL, NULL, NULL, 'VTE', 'Tax Assistant Office', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (95, 'Souksavanh Chanhthavisouk', NULL, NULL, NULL, 'VTE', 'Ccare Team', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (110, 'Thipphachan Norkhamsomphou', NULL, NULL, NULL, 'VTE', 'Reporting Systems Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (111, 'Phonekeo INSARN', NULL, NULL, NULL, 'VTE', 'IT Support', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (112, 'Khuanxay Sonexayyalath', NULL, NULL, NULL, 'VTE', 'SOC Agent', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (113, 'Vuemor', NULL, NULL, NULL, 'VTE', 'Marketing Analyst Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (114, 'Danuphon Khamvongsa', NULL, NULL, NULL, 'VTE', 'Services Operations Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (115, 'Pawari', NULL, NULL, NULL, 'VTE', 'Chief of Finance', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (116, 'Malythao Cherching', NULL, NULL, NULL, 'VTE', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (117, 'Soukphachan Sayakone', NULL, NULL, NULL, 'IT-Stock-Working', NULL, 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (118, 'Choua Vang', NULL, NULL, NULL, 'VTE', 'Software Development API Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (119, 'Likhasith Meuangpak', NULL, NULL, NULL, 'VTE', 'AR Accountant', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (120, 'Anousit Vongpanya', NULL, NULL, NULL, 'VTE', 'Trade Marketing Officer', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (121, 'Matthida phanphonyasith', NULL, NULL, NULL, 'VTE', 'Marketing Analyst Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (122, 'Phengtarn Sounbandith', NULL, NULL, NULL, 'VTE', 'Quality Assurance Coordinator', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (123, 'Vongxai Suvandy', NULL, NULL, NULL, 'VTE', 'IT Support', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (125, 'Souksavanh Chansina', NULL, NULL, NULL, 'VTE', 'Legal Officer', 5, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (126, 'Viengkeo Phaosada', NULL, NULL, NULL, 'VTE', 'Director Secretary', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (127, 'Soukthida Koulavongsa', NULL, NULL, NULL, 'SVK', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (128, 'Xayasith Leetouaxiong', NULL, NULL, NULL, 'VTE', 'Field Operations Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (129, 'Maneenut sayphosy', NULL, NULL, NULL, 'VTE', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (130, 'Vatthana Prokeolasaboud', NULL, NULL, NULL, 'SVK', 'ISP Sales Representative', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (131, 'Kaisone Vilaisouk', NULL, NULL, NULL, 'SVK', 'Sale', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (132, 'khamlar Aoutavisai', NULL, NULL, NULL, 'VTE', 'Developer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (133, 'Tom Huangsavanh', NULL, NULL, NULL, 'VTE', 'Billing Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (135, 'Saisavan Seepaserd', NULL, NULL, NULL, 'VTE', 'Marketing digital media', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (136, 'Chansouk Chanthavong', NULL, NULL, NULL, 'VTE', 'Graphic Design', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (137, 'Sengathid Phafong', NULL, NULL, NULL, 'VTE', 'Student Promoter Supervisor', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (138, 'Viengsavanhthong Sonboulom', NULL, NULL, NULL, 'VTE', 'IR Accountant', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (139, 'Sounthone Phommavong', NULL, NULL, NULL, 'CPS', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (140, 'Soulaxay Chanthakhoun', NULL, NULL, NULL, 'CPS', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (141, 'Fuechang', NULL, NULL, NULL, 'VTE', 'IT Support', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (142, 'Chanthida Vithachit', NULL, NULL, NULL, 'LPB', 'C-Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (143, 'Anousone Keoking', NULL, NULL, NULL, 'LPB', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (144, 'Phoukham Keophiachan', NULL, NULL, NULL, 'XHK', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (145, 'Khamkeng Fongsisavath', NULL, NULL, NULL, 'VTE', 'Field Operations Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (146, 'Yommala xaylaykham', NULL, NULL, NULL, 'VTE', 'SOC Agent', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (147, 'Phonesavanh Sihalath', NULL, NULL, NULL, 'SVK', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (148, 'Sesavang Vongpanya', NULL, NULL, NULL, 'VTE', 'Services Operations Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (150, 'Saythong Xayyalath', NULL, NULL, NULL, 'VTE', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (151, 'Bounum Khammalavong', NULL, NULL, NULL, 'IT-Stock-Working', 'Field Operations Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (152, 'Phaengthanom Manivong', NULL, NULL, NULL, 'VTE', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (153, 'Tingly', NULL, NULL, NULL, 'VTE', 'Field Operations Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (155, 'Chanthasone Xoydala', NULL, NULL, NULL, 'VTE', 'Assistant Budget', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (156, 'Boning Phunthavong', NULL, NULL, NULL, 'VTE', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (157, 'Binly Sengsoulichanh', NULL, NULL, NULL, 'VTE', 'Marketing Analyst Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (158, 'Bounchan Keophongsai', NULL, NULL, NULL, 'VTE', 'Senior VAS Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (159, 'Mithuna Duangchanthong', NULL, NULL, NULL, 'VTE', 'ISO Operation Officer', 5, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (160, 'Bouavone Keomahanin', NULL, NULL, NULL, 'ATP', 'C-Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (161, 'saosanga', NULL, NULL, NULL, 'VTE', 'C-care Onsite Support', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (162, 'Aunnika Keovongvijhid', NULL, NULL, NULL, 'BLK', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (163, 'Khamvingvone Thammavong', NULL, NULL, NULL, 'VTE', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (164, 'Nilanh Phongsawath', NULL, NULL, NULL, 'VTE', 'Administration Services Manager', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (165, 'Thonekeo(SEO)', NULL, NULL, NULL, 'VTE', 'CEO', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (166, 'khamlex Soukhavong', NULL, NULL, NULL, 'VTE', 'Field Operations Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (167, 'Serd Chanthapheng', NULL, NULL, NULL, 'VTE', 'Software Development Application Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (168, 'Synong Bouasyluyanom', NULL, NULL, NULL, 'KHM', 'Regional Sales Executive', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (169, 'Na Khamsoulida', NULL, NULL, NULL, 'VTE', 'Senior Sale Representative', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (170, 'Vilaphong Boubphavong', NULL, NULL, NULL, 'VTE', 'Finance Officer', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (171, 'Pavala Saythala', NULL, NULL, NULL, 'VTE', 'Services Operations Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (172, 'Thongsamay Silakhoune', NULL, NULL, NULL, 'IT-Stock-Working', 'Senior Site Management Specialist', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (173, 'Somlack Phommachack', NULL, NULL, NULL, 'IT-Stock-Working', 'Acting RNE & Planning Senior Manager', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (174, 'Kaikham Pathoumthong', NULL, NULL, NULL, 'VTE', 'HR Organization Development Officer', 5, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (175, 'Lina Khounvilay', NULL, NULL, NULL, 'BOK', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (176, 'Oudone Oudomphone', NULL, NULL, NULL, 'VTE', 'Services Operations Manager', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (177, 'Vongsavay', NULL, NULL, NULL, 'LPB', 'Senior Regional Sales Manager North', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (178, 'Vongvilay Sesomvang', NULL, NULL, NULL, 'VTE', 'Regional Sales Manager North', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (179, 'phoutthasone souliyavong', NULL, NULL, NULL, 'VTE', 'Developer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (180, 'kesone keomany', NULL, NULL, NULL, 'VTE', 'Finance Officer', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (181, 'Siamphone Sisouvong', NULL, NULL, NULL, 'VTE', 'Purchaser', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (182, 'Sithong Phetvilai', NULL, NULL, NULL, 'VTE', 'Reporting Systems Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (183, 'Boubpha Houngthachack', NULL, NULL, NULL, 'VTE', 'IT Developer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (184, 'Settha Piavong', NULL, NULL, NULL, 'VTE', 'Head of Human Resource', 5, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (185, 'Kanha Soulivong', NULL, NULL, NULL, 'VTE', 'Head of Customer Operation', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (186, 'Phanawouth', NULL, NULL, NULL, 'VTE', 'Chief of HR', 5, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (187, 'Chanthala', NULL, NULL, NULL, 'VTE', 'Head of Marketing', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (188, 'Thipkesone luanglath', NULL, NULL, NULL, 'VTE', 'Brands Manager', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (189, 'Mayphone', NULL, NULL, NULL, 'VTE', 'Head of Tech and IT', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (190, 'Arunee PPP', NULL, NULL, NULL, 'VTE', 'Chief of Finance', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (191, 'Thipphaphone', NULL, NULL, NULL, 'VTE', 'Head of Customer Operation', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (192, 'Soudavone Houngthachak', NULL, NULL, NULL, 'VTE', 'Billng System Engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (193, 'Phoutthavong Khammavongkeo', NULL, NULL, NULL, 'VTE', 'CEO', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (194, 'Veokham Khamphilavong', NULL, NULL, NULL, 'VTE', 'Service Operation Center engineer', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (195, 'fasay sivilay', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (196, 'Bouakeo Vannalerd', NULL, NULL, NULL, 'VTE', 'Finance Officer', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (197, 'Naphaphone Kheuakhamvone', NULL, NULL, NULL, 'LTC', 'Quality Assurance Coordinator', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (198, 'Thantavan Lamthong', NULL, NULL, NULL, 'VTE', 'IT Admin Assistant', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (199, 'Koua Lor', NULL, NULL, NULL, 'VTE', 'Marketing Analyst Assistant', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (200, 'Soulichai Chanthavixay', NULL, NULL, NULL, 'VTE', 'Vehicle Team Leader', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (201, 'Dachai Phanthavong', NULL, NULL, NULL, 'SVK', 'Admin Savannakhet', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (202, 'Sien Phommavihan', NULL, NULL, NULL, 'VTE', 'Inventory Assistant', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (203, 'Naphaphone Saenkhamsong', NULL, NULL, NULL, 'VTE', 'VAS Assistant Officer', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (204, 'Deuanpakay Phouthamath', NULL, NULL, NULL, 'VTE', 'Cops Stock Managerment Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (205, 'Chanhdaphone Opphalavong', NULL, NULL, NULL, 'VTE', 'Digital Product and Service Manager', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (206, 'Luddavone Phanthavong', NULL, NULL, NULL, 'VTE', 'HR Officer (Training & OD)', 5, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (207, 'Sangkhom Outhaithammavong', NULL, NULL, NULL, 'VTE', 'Billing Coordinator', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (208, 'Maniphone Khamsili', NULL, NULL, NULL, 'VTE', 'Administration Officer', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (209, 'Choulasin Peersakha', NULL, NULL, NULL, 'SVK', 'Senior RNE Specialist', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (210, 'Lottana XAYSOMBOON', NULL, NULL, NULL, 'VTE', 'Sale', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (211, 'Linna Oumanichan', NULL, NULL, NULL, 'SVK', 'Senior Regional Sales Manager', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (212, 'IT Center', NULL, NULL, NULL, NULL, 'IT Support', NULL, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (214, 'Share', NULL, NULL, NULL, 'VTE', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (215, 'Phoutthanong', NULL, NULL, NULL, 'VTE', 'Sale', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (216, 'Inventory Center', NULL, NULL, NULL, 'VTE', 'Inventory Officer', 1, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (217, 'Phunthavouth Sisongkham', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (218, 'Xaykeo Douangsata', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (219, 'Yealor Lor', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (220, 'SOC Monitoring', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (221, 'Customer Care Agent', NULL, NULL, NULL, 'OUX', 'Customer Care Agent', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (225, 'Isaiah Martinez', 'Facere incidunt vol', '+1 (823) 898-8874', 'm', 'Aut magnam excepturi', 'Ratione earum volupt', 3, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (226, 'Book', '3456dff', '02074346518', 'M', 'Floor3', 'Manager', 4, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (227, 'Trump', '4567gedee', '02054345673', 'M', 'Floor3', 'Dev', 6, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (228, 'Putin', '3456ygfd', '02043456521', 'F', 'Floor1', 'dev', 6, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (231, 'Hoyt Phelps', '05hhhb', '+1 (482) 964-8686', 'm', 'In voluptas consequa', 'Sunt cum assumenda v', 11, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (233, 'Anou Duangpasert', 'wert5435', NULL, NULL, 'VTE', 'Sales Executive(Service provider)', 9, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (234, 'Recycle Bin Raw Test Employee', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL);
INSERT INTO dbo.employee_position_backup ([employee_id], [full_name], [staff_code], [phone], [sex], [location], [position], [department_id], [is_active], [left_date]) VALUES (235, 'Recycle Bin Retest Employee', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL);

